name: Tofu Apply
on: 
  push: 
    branches: ["main"]
    paths:
      - "td5/scripts/tofu/live/**.tf"

jobs: 
  apply: 
    name: "Tofu Apply"
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      id-token: write
      contents: read

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Detect changed OpenTofu directories
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          dir_names: true
          path: "td5/scripts/tofu/live/"
          separator: ","

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::054037125242:role/lambda-sample-apply
          role-session-name: apply-${{ github.run_number }}-${{ github.actor }}
          aws-region: us-east-2

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Run OpenTofu Apply on changed directories
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          for dir in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Running tofu apply in $dir"
            cd "$dir"
            tofu init -no-color -input=false
            tofu apply -no-color -input=false -lock-timeout=60m -auto-approve
            cd - > /dev/null
          done
