name: Tofu Plan
on: 
  pull_request: 
    branches: ["main"]
    paths: ["td5/scripts/tofu/live/**.tf"]
    
jobs: 
  plan: 
    name: "Tofu Plan"
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      id-token: write
      contents: read
      
    steps: 
      
      - uses: actions/checkout@v2
      - name: Detect changed OpenTofu directories
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          dir_names: true
          path: "td5/scripts/tofu/live/"
          separator: ","

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          # TODO: fill in your IAM role ARN!
          role-to-assume: arn:aws:iam::054037125242:role/lambda-sample-plan
          role-session-name: plan-${{ github.run_number }}-${{ github.actor }}
          aws-region: us-east-2
          
      - uses: opentofu/setup-opentofu@v1
      
      - name: tofu plan
        id: plan
        working-directory: td5/scripts/tofu/live/**
        run: |
          tofu init -no-color -input=false
          tofu plan -no-color -input=false -lock=false

      - uses: peter-evans/create-or-update-comment@v4
        if: always()
        env:
          RESULT_EMOJI: ${{ steps.plan.outcome == 'success' && '✅' || '⚠' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ${{ env.RESULT_EMOJI }} `tofu plan` output
            ```${{ steps.plan.outputs.stdout }}`
      
      - uses: opentofu/setup-opentofu@v1
      - name: Run OpenTofu Plan on changed directories
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          for dir in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Running tofu plan in $dir"
            cd "$dir"
            tofu init -no-color -input=false
            tofu plan -no-color -input=false -lock=false
            cd - > /dev/null
          done
